/*
--CADASTROS

DELETE FROM FABRICA;
DELETE FROM SETOR;
DELETE FROM CLASSIFICACAO_FISCAL;
DELETE FROM CONDICAO_PAGAMENTO;
DELETE FROM CONTA_BANCARIA;
DELETE FROM CORES;
DELETE FROM FABRICA;
DELETE FROM FACA;
DELETE FROM FAMILIA_PRODUTOS;
DELETE FROM FORMA;
DELETE FROM CLASSIFICACAO_DT;
DELETE FROM CLASSIFICACAO;
DELETE FROM GRUPO_CLIENTE;
DELETE FROM MARCA;
DELETE FROM FORNECEDOR;
DELETE FROM BANCA;
DELETE FROM SETOR;
DELETE FROM MEDIDA;
DELETE FROM GRADE_ESPECIAL;
DELETE FROM GRADE_ESPECIAL_ORDENADA;
DELETE FROM GRADE_PADRAO_DT;
DELETE FROM GRADE_PADRAO;

--PRODUÇÃO

DELETE FROM TIPO_lINHA;
DELETE FROM PEDIDO;
DELETE FROM MODELOS;
DELETE FROM LINHA;

--SUPRIMENTOS

DELETE FROM COMPRAS_ENTREGA_ITEM_GRADE;
DELETE FROM COMPRAS_ENTREGA_ITEM;
DELETE FROM COMPRAS_ENTREGA;
DELETE FROM ORDEM_COMPRA_ITEM_GRADE;
DELETE FROM ORDEM_COMPRA_ITEM;
DELETE FROM ORDEM_COMPRA;
DELETE FROM SUB_GRUPO;
DELETE FROM GRUPO_MATERIAL;

--FINANCEIRO
DELETE FROM LANCAMENTO_FINANCEIRO;
DELETE FROM PRODUTO_NF;

INSERT INTO GRADE_ESPECIAL (B13, B14, B15, B16, B17, B18, B19, B20, B21, B22, B23, B24, B25, B26, B27, B28, B29, B30, B31, B32, B33, B34, B35, B36, B37, B38, B39, B40, B41, B42, B43, B44, B45, B46, B47, B48, B49, B50, B51, B52, B53, B54, B55)
                    VALUES ('13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT WORK;

INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (1, '13', 1, 13);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (2, '14', 2, 14);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (3, '15', 3, 15);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (4, '16', 4, 16);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (5, '17', 5, 17);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (6, '18', 6, 18);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (7, '19', 7, 19);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (8, '20', 8, 20);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (9, '21', 9, 21);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (10, '22', 10, 22);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (11, '23', 11, 23);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (12, '24', 12, 24);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (13, '25', 13, 25);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (14, '26', 14, 26);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (15, '27', 15, 27);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (16, '28', 16, 28);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (17, '29', 17, 29);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (18, '30', 18, 30);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (19, '31', 19, 31);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (20, '32', 20, 32);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (21, '33', 21, 33);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (22, '34', 22, 34);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (23, '35', 23, 35);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (24, '36', 24, 36);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (25, '37', 25, 37);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (26, '38', 26, 38);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (27, '39', 27, 39);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (28, '40', 28, 40);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (29, '41', 29, 41);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (30, '42', 30, 42);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (31, '43', 31, 43);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (32, '44', 32, 44);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (33, '45', 33, 45);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (34, NULL, 34, 46);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (35, NULL, 35, 47);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (36, NULL, 36, 48);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (37, NULL, 37, 49);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (38, NULL, 38, 50);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (39, NULL, 39, 51);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (40, NULL, 40, 52);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (41, NULL, 41, 53);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (42, NULL, 42, 54);
INSERT INTO GRADE_ESPECIAL_ORDENADA (ID_GRADE_ESPECIAL_ORDENADA, GRADE_ESPECIAL, ORDEM, TAMANHO)
                             VALUES (43, NULL, 43, 55);

COMMIT WORK;

*/
