function Test1()
{
  var sidi;
  var tfrmPrincipal;
  var tfrmTabelaPrecos;
  var groupBox;
  var twwDBGrid;
  var speedButton;
  var tfrmProdutosTabelaPrecos;
  var notebook;
  var panel;
  var panel2;
  var radioGroup;
  var groupButton;
  var groupButton2;
  var groupButton3;
  var btnWinControl;
  var twwPopupGrid;
  var tfrmOutrosFiltros;
  var twwDBGrid2;
  var currencyEdit;
  var bitBtn;
  sidi = Aliases.SIDI;
  tfrmPrincipal = sidi.frmPrincipal;
  tfrmPrincipal.btnTabelaPrecos.Click(14, 11);
  tfrmTabelaPrecos = tfrmPrincipal.MDIClient.frmTabelaPrecos;
  tfrmTabelaPrecos.sbNovo.Click(23, 10);
  groupBox = tfrmTabelaPrecos.gbTabela;
  twwDBGrid = groupBox.SelecionaTabela;
  twwDBGrid.VScroll.Pos = 0;
  twwDBGrid.Click(87, 29);
  speedButton = tfrmTabelaPrecos.sbSalvar;
  speedButton.Click(28, 6);
  tfrmTabelaPrecos.sbImportar.Click(53, 9);
  tfrmProdutosTabelaPrecos = sidi.frmProdutosTabelaPrecos;
  notebook = tfrmProdutosTabelaPrecos.Notebook1;
  panel = notebook.TPage;
  panel2 = panel.Panel4;
  radioGroup = panel2.rgImportar;
  radioGroup.TGroupButton.ClickButton();
  groupButton = radioGroup.TGroupButton2;
  groupButton.ClickButton();
  radioGroup.TGroupButton3.ClickButton();
  radioGroup.TGroupButton4.ClickButton();
  groupButton2 = radioGroup.TGroupButton5;
  groupButton2.ClickButton();
  groupButton3 = radioGroup.TGroupButton6;
  groupButton3.ClickButton();
  groupButton2.ClickButton();
  twwDBGrid = panel2.gbCondicoes.GridCondicoes;
  twwDBGrid.VScroll.Pos = 0;
  twwDBGrid.Click(228, 21);
  twwDBGrid.Click(226, 27);
  twwDBGrid.Click(35, 33);
  groupButton3.ClickButton();
  btnWinControl = panel2.gbTipo.cblReferencia.TBtnWinControl;
  btnWinControl.Click(7, 10);
  groupButton.ClickButton();
  btnWinControl.Click(3, 11);
  twwPopupGrid = sidi.TwwPopupGrid;
  twwPopupGrid.Click(98, 5);
  tfrmProdutosTabelaPrecos.sbOutrosFiltrosLinhaRef.Click(9, 13);
  tfrmOutrosFiltros = sidi.frmOutrosFiltros;
  twwDBGrid = tfrmOutrosFiltros.ntbkOutrosFiltros.TPage.gbLinhas.gdLinhas;
  twwDBGrid.VScroll.Pos = 0;
  twwDBGrid.Click(21, 12);
  twwDBGrid.Click(21, 25);
  tfrmOutrosFiltros.PnlBotoes.btnConfirmar.ClickButton();
  panel.Panel3.btnImportar.ClickButton();
  speedButton.Click(21, 14);
  twwDBGrid = tfrmTabelaPrecos.Panel1.gbProdutos.GridProdutos;
  twwDBGrid.HScroll.Pos = 0;
  twwDBGrid.VScroll.Pos = 0;
  twwDBGrid.Click(42, 30);
  twwDBGrid.Click(42, 42);
  twwDBGrid.VScroll.Pos = 2;
  twwDBGrid.Click(43, 58);
  tfrmTabelaPrecos.spIncluirCondicoes.Click(49, 18);
  panel = notebook.TPage2;
  panel2 = panel.Panel1;
  twwDBGrid2 = panel2.GroupBox1.dbgSelecioneCondicao;
  twwDBGrid2.VScroll.Pos = 0;
  twwDBGrid2.Click(35, 31);
  currencyEdit = panel2.EditPreco;
  currencyEdit.DblClick(37, 12);
  bitBtn = panel.Panel2.btnAvancar;
  bitBtn.ClickButton();
  speedButton.Click(40, 9);
  panel = groupBox.gbObs.Panel3;
  panel.TRANSPORTADORA.TBtnWinControl.Click(4, 4);
  twwPopupGrid.Click(40, 55);
  panel.COTACAO.TBtnWinControl.Click(2, 8);
  sidi.TwwPopupListbox.Click(63, 7);
  panel.DESCONTOS.Click(31, 12);
  panel.FRETE.Click(36, 8);
  panel.COMISSAO.Click(13, 16);
  panel.COMISSAO_PREPOSTO.Click(13, 5);
  panel.DESCONTO_VISTA.Click(20, 6);
  panel.FILTRAR_TABELA_CIDADE.TGroupButton.ClickButton();
  panel.FRETE_CONTA.TGroupButton.ClickButton();
  panel.BLOQ_SIDI_MOBILE.TGroupButton.ClickButton();
  panel.BLOQUEAR.TGroupButton.ClickButton();
  twwDBGrid.Click(411, 59);
  twwDBGrid.Click(416, 45);
  twwDBGrid.Click(434, 27);
  twwDBGrid.Click(419, 48);
  twwDBGrid.Click(416, 65);
  tfrmTabelaPrecos.sbImportarCondicoes.Click(72, 14);
  twwDBGrid2.VScroll.Pos = 2;
  twwDBGrid2.Click(33, 30);
  currencyEdit.Click(13, 4);
  bitBtn.ClickButton();
  twwDBGrid.Click(320, 47);
  twwDBGrid.Click(320, 35);
  speedButton.Click(27, 12);
}